name = "VisuTwinSim"
uuid = "8f2f2ac6-9a0f-4b36-bcf4-6fb8b7f9474d"
authors = ["Arnis Lektauers <arnis.lektauers@rtu.lv>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
VisuTwinSimCUDAExt = ["CUDA"]

[compat]
CUDA = "5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
